version: '3.8'
services:
  reverse_proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  app:
    image: voicerecognition
    labels:
      - "traefik.http.routers.app.rule=Host(`lavanpa.online`)"
    deploy:
      modes:
        - replicated
      replicas: 3
    restart: unless-stopped
