services:
  app:
    image: voicerecognition
    container_name: voicerecognition_container
    networks:
      - caddy
    expose:             # Only expose to Docker network (no host port)
      - "80"
    restart: unless-stopped

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"        # Host ports for HTTP/HTTPS
      - "443:443"
      - "127.0.0.1:2019:2019"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  # Bind mount your local Caddyfile
      - caddy_data:/data                 # Persistent certs
      - caddy_config:/config              # Caddy’s config DB
    networks:
      - caddy
    # In docker-compose.yml (caddy service)
    environment:
      - CADDY_ADMIN=:2019

volumes:
  caddy_data:          # Caddy’s TLS certificates
  caddy_config:        # Caddy’s auto-saved config

networks:
  caddy: